"""Allow for nullable task_id

Revision ID: a30621e7a676
Revises: 
Create Date: 2025-12-26 02:18:12.223330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a30621e7a676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.alter_column('task', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('task', 'task_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index(op.f('ix_task_task_id'), table_name='task')
    op.create_unique_constraint(None, 'task', ['id'])
    op.create_unique_constraint(None, 'task', ['task_id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_constraint(None, 'task', type_='unique')
    op.create_index(op.f('ix_task_task_id'), 'task', ['task_id'], unique=True)
    op.alter_column('task', 'task_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('task', 'document_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
